### ISSUE TITLE
Why Ubuntu `obs-studio` does not have `Browser` source while the official PPA does?

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/obs-studio#10]
https://obsproject.com/download

https://obsproject.com/forum/threads/no-browser-source-in-ubuntu-linux.138125/post-636954

Does Debian also have the issue?

This feature was introduced since what version?

What does this feature looks like ? To see if the considered version has it.

![image](https://github.com/Benjamin-Loison/obs-studio/assets/12752145/931f769a-e391-4ae1-ad01-d20d37cb96b9)

- Linux Mint OBS 27.2.3
- Debian 29.0.2.1

do not seem to have this feature.

On Debian:

https://obsproject.com/download `Ubuntu Instructions (22.04+)`:

```bash
sudo add-apt-repository ppa:obsproject/obs-studio
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
```
</details>

So considering the only other alternative being Flatpak, I get OBS 30.1.1

+2

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Do not have the error on Linux Mint 22 Cinnamon at least for:</summary>

```
-----BEGIN PGP MESSAGE-----

hF4DTQa9Wom5MBgSAQdA03yaBBUrxMnuBiytXUpcprNCygJVJf9XriX6N1vnVEsw
IUqImeMDl/B65cBZvrq5G8lh+53QNHrggg7gam8YTjxHd1h/n/N0Fw+VCebRDbkB
0kAB8vI7DSoQA2NeVF/uvRb1XIlfihxZOhT+Whn1q6XYprX3ryUpA8xrNAZY1+VH
ZJSgIWkQyY3VQkl91lr4pnXl
=27wV
-----END PGP MESSAGE-----
```
</details>
